
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WindowsFormsCanin
{

using System;
    using System.Collections.Generic;
    
public partial class BATARD
{

    public string codechien { get; set; }

    public string codeproprietaire { get; set; }

    public string caracteristiques { get; set; }

}

}
